name: Docker CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - Dockerfile
      - tools/install-dependencies

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v3
#    - name: Lint Dockerfile
#      run: |
#        curl -L https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-Linux-x86_64 -o hadolint && chmod +x hadolint
#        ./hadolint Dockerfile

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # Generate Docker tags based on the following events/attributes.
        tags: |
          # Set tag="master" on each push to master branch.
          type=ref,event=branch
          # Set tag="1.2.3" on each tag push.
          type=semver,pattern={{version}}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Dockerfile
      uses: docker/build-push-action@v4
      with:
        repository: satoshiotomakan/test-repo
        tags: ${{ steps.meta.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
