name: Docker CI

on:
  push:
    branches: [ master ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ master ]
    paths:
      - Dockerfile
      - tools/install-dependencies

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Push docker image to Amazon ECR Public
      # Run on push commit to master branch only.
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Hello world"

